### ISSUE TITLE
SeeSaw Issue - OSError: [Errno 5] Input/output error

### ISSUE THREAD

**Issue by wallarug** [robotics-masters/mm1-hat-seesaw#6]
```
>>> ss.pin_mode(BUTTON, ss.INPUT_PULLUP)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.5/site-packages/adafruit_seesaw/seesaw.py", line 177, in pin_mode
    self.pin_mode_bulk_b(1 << (pin - 32), mode)
  File "/home/pi/.local/lib/python3.5/site-packages/adafruit_seesaw/seesaw.py", line 281, in pin_mode_bulk_b
    self.write(_GPIO_BASE, _GPIO_DIRCLR_BULK, cmd)
  File "/home/pi/.local/lib/python3.5/site-packages/adafruit_seesaw/seesaw.py", line 404, in write
    i2c.write(full_buffer)
  File "/home/pi/.local/lib/python3.5/site-packages/adafruit_bus_device/i2c_device.py", line 115, in write
    self.i2c.writeto(self.device_address, buf, **kwargs)
  File "/home/pi/.local/lib/python3.5/site-packages/busio.py", line 65, in writeto
    return self._i2c.writeto(address, buffer, stop=stop)
  File "/home/pi/.local/lib/python3.5/site-packages/adafruit_blinka/microcontroller/generic_linux/i2c.py", line 38, in writeto
    self._i2c_bus.write_bytes(address, buffer[start:end])
  File "/home/pi/.local/lib/python3.5/site-packages/Adafruit_PureIO/smbus.py", line 244, in write_bytes
    self._device.write(buf)
OSError: [Errno 5] Input/output error

```
![image](https://user-images.githubusercontent.com/11770912/53407689-d9d4cb00-3a10-11e9-9ab5-f17aa1864f9e.png)

**Comment by wallarug** [comment]
I have been working through the code matching up the configurations.  It appears that SeeSaw does it's own thing by setting the Pin map independently of everything else.

Line 155 - [seesaw.py](https://github.com/adafruit/Adafruit_CircuitPython_seesaw/blob/master/adafruit_seesaw/seesaw.py)
```
        pid = self.get_version() >> 16
        if pid == _CRICKIT_PID:
            from adafruit_seesaw.crickit import Crickit_Pinmap
            self.pin_mapping = Crickit_Pinmap
        else:
            from adafruit_seesaw.samd09 import SAMD09_Pinmap
            self.pin_mapping = SAMD09_Pinmap
```

I am going to change this bit and see what happens.

**Comment by wallarug** [comment]
SeeSaw is doing absolutely nothing.  No errors, no output.

![screenshot from 2019-03-02 00-38-07](https://user-images.githubusercontent.com/11770912/53641576-8b7b3280-3c83-11e9-93e6-eb06d8132e70.png)

**Comment by wallarug** [comment]
Isolated issue down to two things:
1.  SIGNALs that are not mentioned in the firmware do not do anything.
2.  SERVO control is broken and producing below error:

![image](https://user-images.githubusercontent.com/11770912/53642080-fd07b080-3c84-11e9-9c0a-1315a2bed8a1.png)

**Comment by wallarug** [comment]
This was resolved in a later commit.  If issue represents itself, we can reopen.

**Comment by wallarug** [comment]
See issue: https://github.com/adafruit/seesaw/issues/17 for further details on issue.
